/* groovylint-disable LineLength */
/* groovylint-disable-next-line CompileStatic */
pipeline {
  agent any
  environment {
      ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }
  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

  stages {
    stage('Initial Cleanup') {
      steps {
        dir("${WORKSPACE}") {
          deleteDir()
        }
      }
    }
    stage('Checkout SCM') {
      steps {
        git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/adeadedeji72/ansible-config.git'
      }
    }
    stage('Prepare Ansible for Execusion') {
      steps {
        sh 'echo ${WORKSPACE}'
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
      }
    }
    stage('Run Ansible Playbook') {
      steps {
        /* groovylint-disable-next-line GStringExpressionWithinString */
        ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
      }
    }
    stage('Clean Workspace after buil') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }
  }
}
